#pragma once

#define VER_FILE_GGDATAAPI_MAJOR	1
#define VER_FILE_GGDATAAPI_MINOR	0
#define VER_FILE_GGDATAAPI_BUILD	1
#define VER_FILE_GGDATAAPI_SVN		3564

#define VER_FILE_GGDATAAPI_REVISION "1.0.1.3564"
