#pragma once

#define VER_PRODUCE_GGDATAAPI_MAJOR		1
#define VER_PRODUCE_GGDATAAPI_MINOR		0
#define VER_PRODUCE_GGDATAAPI_REVISE	1
#define VER_PRODUCE_GGDATAAPI_LEVEL		1

#define VER_PRODUCE_GGDATAAPI_REVISION  "1.0.1.1"
