#pragma once
#define VER_FILE_GGJSONCPP_MAJOR	1
#define VER_FILE_GGJSONCPP_MINOR	0
#define VER_FILE_GGJSONCPP_BUILD	1
#define VER_FILE_GGJSONCPP_SVN	3595

#define VER_FILE_GGJSONCPP_REVISION "1.0.1.3595"
